"""empty message

Revision ID: 098ae8880431
Revises: 62c31ff3d3fe
Create Date: 2022-11-18 12:18:46.208665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098ae8880431'
down_revision = '62c31ff3d3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=True),
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('cocina_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('comentario', sa.String(length=250), nullable=True),
    sa.Column('metodo', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.String(length=250), nullable=True),
    sa.Column('destino', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['cocina_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_carrito'], ['carritos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    # ### end Alembic commands ###
