"""empty message

Revision ID: 1ef18e374214
Revises: f7d5f1193897
Create Date: 2022-11-01 01:37:54.505039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef18e374214'
down_revision = 'f7d5f1193897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('foto', sa.String(length=250), nullable=True))
    op.add_column('usuarios', sa.Column('direccion', sa.String(length=250), nullable=True))
    op.add_column('usuarios', sa.Column('facebook', sa.String(length=250), nullable=True))
    op.add_column('usuarios', sa.Column('twitter', sa.String(length=250), nullable=True))
    op.add_column('usuarios', sa.Column('linkedin', sa.String(length=250), nullable=True))
    op.add_column('usuarios', sa.Column('instragram', sa.String(length=250), nullable=True))
    op.add_column('usuarios', sa.Column('dribble', sa.String(length=250), nullable=True))
    op.add_column('usuarios', sa.Column('pinterest', sa.String(length=250), nullable=True))
    op.alter_column('usuarios', 'telefono',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'telefono',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_column('usuarios', 'pinterest')
    op.drop_column('usuarios', 'dribble')
    op.drop_column('usuarios', 'instragram')
    op.drop_column('usuarios', 'linkedin')
    op.drop_column('usuarios', 'twitter')
    op.drop_column('usuarios', 'facebook')
    op.drop_column('usuarios', 'direccion')
    op.drop_column('usuarios', 'foto')
    # ### end Alembic commands ###
