"""empty message

Revision ID: 3ea15f5b66f3
Revises: 641dffd21d86
Create Date: 2022-11-01 01:47:06.880556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea15f5b66f3'
down_revision = '641dffd21d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('departamento', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.String(length=250), nullable=True),
    sa.Column('mail', sa.String(length=250), nullable=True),
    sa.Column('foto', sa.String(length=250), nullable=True),
    sa.Column('opcion', sa.String(length=250), nullable=False),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactos')
    # ### end Alembic commands ###
