"""empty message

Revision ID: 641dffd21d86
Revises: b252452861bf
Create Date: 2022-11-01 01:43:41.452509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641dffd21d86'
down_revision = 'b252452861bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias__productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias__productos')
    # ### end Alembic commands ###
