"""empty message

Revision ID: 8362ef2aefb8
Revises: 44d9092dab83
Create Date: 2022-11-01 20:44:14.479386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8362ef2aefb8'
down_revision = '44d9092dab83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carritos', sa.Column('nro_renglon', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carritos', 'nro_renglon')
    # ### end Alembic commands ###
