"""empty message

Revision ID: 9194d2c48745
Revises: 8362ef2aefb8
Create Date: 2022-11-02 15:54:10.393333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9194d2c48745'
down_revision = '8362ef2aefb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carritos', sa.Column('id_carrito', sa.Integer(), nullable=False))
    op.drop_column('carritos', 'nro_renglon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carritos', sa.Column('nro_renglon', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('carritos', 'id_carrito')
    # ### end Alembic commands ###
