"""empty message

Revision ID: b6902a579fa8
Revises: 9194d2c48745
Create Date: 2022-11-07 12:31:14.729578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6902a579fa8'
down_revision = '9194d2c48745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('descripcion', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'descripcion')
    # ### end Alembic commands ###
