"""empty message

Revision ID: f7d5f1193897
Revises: dc6c7e7e93fa
Create Date: 2022-10-28 02:16:32.111774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d5f1193897'
down_revision = 'dc6c7e7e93fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puntuaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('cocina_id', sa.Integer(), nullable=True),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cocina_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puntuaciones')
    # ### end Alembic commands ###
